#version: '2'
#services:
#  php:
#    image: yiisoftware/yii2-php:7.4-apache
#    volumes:
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated
#    ports:
#      - '8000:80'

version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: docker_data_nginx
    volumes:
      - "./:/var/www"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3003:80"
      - "453:443"
    environment:
      - NGINX_HOST=localhost
    #        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: "no"
    depends_on:
      - app
      - mysqldb
    networks:
      - app_default
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: task_force_php
    restart: "no"
    volumes:
      - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - mysqldb
    networks:
      - app_default
  mysqldb:
    image: mysql:8.0
    container_name: task_force_mysql
    restart: "no"
    environment:
      - MYSQL_DATABASE=task_force
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3316:3306"
    volumes:
      - "./docker_data/db/mysql:/var/lib/mysql"
    networks:
      - app_default

networks:
  app_default:
    driver: bridge
